[package]
name = "langfuse"
version = "0.1.7"
edition = "2024"
authors = ["Adolfo Usier <adolfousier@gmail.com>"]
description = "A simple Rust client for the Langfuse.com observability platform by Neura AI"
license = "MIT"
repository = "https://github.com/adolfousier/langfuse-rust"
documentation = "https://docs.rs/langfuse"
readme = "README.md"
keywords = ["langfuse", "observability", "tracing", "monitoring", "llm"]
categories = ["development-tools", "api-bindings", "development-tools::debugging"]

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
base64 = "0.22.1"
thiserror = "1.0"

[dev-dependencies]
tokio = { version = "1.0", features = ["full"] }
